version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run_tests:
    docker:
      - image:  circleci/node:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
          POSTGRES_PASSWORD: mypass

    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
    working_directory: ~/repo
    steps:
        - run:
            name: Install ltree extension for Postgres
            command: |
              sudo apt-get update
              sudo apt-get install postgresql-client
              dockerize -wait tcp://localhost:5432 -timeout 1m
              psql -U circleci -h localhost -p 5432 -c 'create extension ltree'
        - checkout
        - run:
            name: update-yarn
            command: 'yarn install --save'
        - run:
            name: Run tests
            command: yarn test
            when: always
        - run:
            name: Run coverage
            command: yarn run coverage
            when: always
        - run:
            name: Setup Code Climate test-reporter
            command: |
                # download test reporter as a static binary
                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                chmod +x ./cc-test-reporter
                ./cc-test-reporter before-build
            when: always
        - run:
            name: Send coverage report to Code Climate
            command:
                ./cc-test-reporter after-build -t lcov
            when: always
        - store_artifacts:
            path: ./coverage/lcov.info
            prefix: tests
workflows:
  builds:
    jobs:
      - run_tests
